name: Rebuild

on:
  push:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        hytale-tag: [release, pre-release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Get latest commit hash
        run: echo "LATEST_COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Get latest version
        run: echo "VERSION=0.1.1" >> $GITHUB_ENV
      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils
      - name: Get latest hytale version for ${{ matrix.hytale-tag }}
        run: |
          HYTALE_VERSION=$(curl -fsSL https://maven.hytale.com/${{ matrix.hytale-tag }}/com/hypixel/hytale/Server/maven-metadata.xml | xmllint --xpath "string(//metadata/versioning/latest)" -)
          echo "Latest version: $HYTALE_VERSION"
          echo "HYTALE_VERSION=$HYTALE_VERSION" >> $GITHUB_ENV
      - name: Set up Java 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: maven
      - name: Build for ${{ matrix.hytale-tag }}
        run: mvn clean package -Drevision=$VERSION-$LATEST_COMMIT_HASH -Dhytale-version=$HYTALE_VERSION
      - name: Upload ${{ matrix.hytale-tag }} artifact
        uses: actions/upload-artifact@v6
        with:
          name: HytaleMoonbaseTTS for ${{ matrix.hytale-tag }} server tag
          path: ./target/HytaleMoonbaseTTS-*.jar
          if-no-files-found: error
      - name: Upload to modtale
        if: ${{ matrix.hytale-tag == 'release' }}
        run: |
          UPLOAD_VERSION="${VERSION}-${LATEST_COMMIT_HASH}"
          JAR_PATH=$(find target -type f -name 'HytaleMoonbaseTTS-*.jar' | head -n 1)

          echo "Found Jar: $JAR_PATH"
          echo "Publishing Version: $UPLOAD_VERSION"

          curl --fail-with-body -X POST "https://api.modtale.net/api/v1/projects/${{ vars.PROJECT_ID }}/versions" \
            -H "X-MODTALE-KEY: ${{ secrets.MODTALE_TOKEN }}" \
            -F "file=@$JAR_PATH" \
            -F "versionNumber=$UPLOAD_VERSION" \
            -F "gameVersions=$HYTALE_VERSION" \
            -F "channel=BETA" \
            -F "changelog=Automated Build & Release from GitHub"
