name: Rebuild

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Get latest commit hash
        run: echo "LATEST_COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Set up Java 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - name: Build fatjar
        run: mvn clean package -P fatjar -Drevision=$LATEST_COMMIT_HASH
      - name: Build with libby
        run: mvn clean package -P with-libby -Drevision=$LATEST_COMMIT_HASH
      - uses: actions/upload-artifact@v6
        with:
          name: HytaleMoonbaseTTS-libby
          path: ./target/with-libby/HytaleMoonbaseTTS-*.jar
      - uses: actions/upload-artifact@v6
        with:
          name: HytaleMoonbaseTTS-fatjar
          path: ./target/fatjar/HytaleMoonbaseTTS-*.jar